enum KeyboardKey: Hashable {
    case digit0
    case digit1
    case digit2
    case digit3
    case digit4
    case digit5
    case digit6
    case digit7
    case digit8
    case digit9
    case letterA
    case letterB
    case letterC
    case letterD
    case letterE
    case letterF
    case letterG
    case letterH
    case letterI
    case letterJ
    case letterK
    case letterL
    case letterM
    case letterN
    case letterO
    case letterP
    case letterQ
    case letterR
    case letterS
    case letterT
    case letterU
    case letterV
    case letterW
    case letterX
    case letterY
    case letterZ
    case comma
    case period
    case semicolon
    case slash
    case minus
    // Unused by the standard arrangement. Milestone 9 places punctuation on the
    // bracket keys; Milestone 10 uses quote and equal for other arrangements.
    case quote
    case equal
    case leftBracket
    case rightBracket
    case backslash
    case space
    case deleteBackward
    case escape
    case returnKey
    case keypadEnter
}
