struct StandardZhuyinLayout: KeyboardLayout {
    func component(for key: KeyboardKey) -> BopomofoComponent? {
        switch key {
        case .digit1: return .initial(.b)
        case .letterQ: return .initial(.p)
        case .letterA: return .initial(.m)
        case .letterZ: return .initial(.f)
        case .digit2: return .initial(.d)
        case .letterW: return .initial(.t)
        case .letterS: return .initial(.n)
        case .letterX: return .initial(.l)
        case .letterE: return .initial(.g)
        case .letterD: return .initial(.k)
        case .letterC: return .initial(.h)
        case .letterR: return .initial(.j)
        case .letterF: return .initial(.q)
        case .letterV: return .initial(.x)
        case .digit5: return .initial(.zh)
        case .letterT: return .initial(.ch)
        case .letterG: return .initial(.sh)
        case .letterB: return .initial(.r)
        case .letterY: return .initial(.z)
        case .letterH: return .initial(.c)
        case .letterN: return .initial(.s)
        case .letterU: return .medial(.i)
        case .letterJ: return .medial(.u)
        case .letterM: return .medial(.yu)
        case .digit8: return .final(.a)
        case .letterI: return .final(.o)
        case .letterK: return .final(.e)
        case .comma: return .final(.eh)
        case .digit9: return .final(.ai)
        case .letterO: return .final(.ei)
        case .letterL: return .final(.ao)
        case .period: return .final(.ou)
        case .digit0: return .final(.an)
        case .letterP: return .final(.en)
        case .semicolon: return .final(.ang)
        case .slash: return .final(.eng)
        case .minus: return .final(.er)
        case .space: return .tone(.first)
        case .digit6: return .tone(.second)
        case .digit3: return .tone(.third)
        case .digit4: return .tone(.fourth)
        case .digit7: return .tone(.neutral)
        case .deleteBackward, .escape, .returnKey, .keypadEnter:
            return nil
        }
    }
}
